// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5cs6Tlb9l_oxMmq0kTn2_1vb6hm3XDAc',
    appId: '1:801622912874:web:bb9e70d17c3f89b508bf13',
    messagingSenderId: '801622912874',
    projectId: 'ma-boutique-12b43',
    authDomain: 'ma-boutique-12b43.firebaseapp.com',
    storageBucket: 'ma-boutique-12b43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJM-VI3U9EVVXJaO8owpJEeQtL-LD3DU',
    appId: '1:801622912874:android:37c4a7788b2d8bdf08bf13',
    messagingSenderId: '801622912874',
    projectId: 'ma-boutique-12b43',
    storageBucket: 'ma-boutique-12b43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKz6p1Ee8yDJnUoCKZH95DCc1VUaTdCAU',
    appId: '1:801622912874:ios:8330f3f00fc814e108bf13',
    messagingSenderId: '801622912874',
    projectId: 'ma-boutique-12b43',
    storageBucket: 'ma-boutique-12b43.firebasestorage.app',
    iosBundleId: 'com.example.maBoutique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKz6p1Ee8yDJnUoCKZH95DCc1VUaTdCAU',
    appId: '1:801622912874:ios:8330f3f00fc814e108bf13',
    messagingSenderId: '801622912874',
    projectId: 'ma-boutique-12b43',
    storageBucket: 'ma-boutique-12b43.firebasestorage.app',
    iosBundleId: 'com.example.maBoutique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5cs6Tlb9l_oxMmq0kTn2_1vb6hm3XDAc',
    appId: '1:801622912874:web:1a1984c73edacd5708bf13',
    messagingSenderId: '801622912874',
    projectId: 'ma-boutique-12b43',
    authDomain: 'ma-boutique-12b43.firebaseapp.com',
    storageBucket: 'ma-boutique-12b43.firebasestorage.app',
  );
}
